//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.Model {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAF.Model.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string System_Action_Add {
            get {
                return ResourceManager.GetString("System_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string System_Action_Approve {
            get {
                return ResourceManager.GetString("System_Action_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string System_Action_Cancel {
            get {
                return ResourceManager.GetString("System_Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string System_Action_Close {
            get {
                return ResourceManager.GetString("System_Action_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string System_Action_Delete {
            get {
                return ResourceManager.GetString("System_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string System_Action_Edit {
            get {
                return ResourceManager.GetString("System_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string System_Action_Export {
            get {
                return ResourceManager.GetString("System_Action_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string System_Action_Inport {
            get {
                return ResourceManager.GetString("System_Action_Inport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆 的本地化字符串。
        /// </summary>
        public static string System_Action_LoginIn {
            get {
                return ResourceManager.GetString("System_Action_LoginIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string System_Action_LoginOut {
            get {
                return ResourceManager.GetString("System_Action_LoginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它 的本地化字符串。
        /// </summary>
        public static string System_Action_Others {
            get {
                return ResourceManager.GetString("System_Action_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索 的本地化字符串。
        /// </summary>
        public static string System_Action_Query {
            get {
                return ResourceManager.GetString("System_Action_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退回 的本地化字符串。
        /// </summary>
        public static string System_Action_Reject {
            get {
                return ResourceManager.GetString("System_Action_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string System_Action_Reset {
            get {
                return ResourceManager.GetString("System_Action_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string System_Action_Save {
            get {
                return ResourceManager.GetString("System_Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string System_Action_Submit {
            get {
                return ResourceManager.GetString("System_Action_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string System_Action_Update {
            get {
                return ResourceManager.GetString("System_Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string System_Info_Hint {
            get {
                return ResourceManager.GetString("System_Info_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据新增失败! 的本地化字符串。
        /// </summary>
        public static string System_Message_AddFail {
            get {
                return ResourceManager.GetString("System_Message_AddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据新增成功! 的本地化字符串。
        /// </summary>
        public static string System_Message_AddSuccess {
            get {
                return ResourceManager.GetString("System_Message_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核通过! 的本地化字符串。
        /// </summary>
        public static string System_Message_Approve {
            get {
                return ResourceManager.GetString("System_Message_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认新增? 的本地化字符串。
        /// </summary>
        public static string System_Message_ConfirmAdd {
            get {
                return ResourceManager.GetString("System_Message_ConfirmAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认取消? 的本地化字符串。
        /// </summary>
        public static string System_Message_ConfirmCancel {
            get {
                return ResourceManager.GetString("System_Message_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除？ 的本地化字符串。
        /// </summary>
        public static string System_Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("System_Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认保存? 的本地化字符串。
        /// </summary>
        public static string System_Message_ConfirmSave {
            get {
                return ResourceManager.GetString("System_Message_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认提交? 的本地化字符串。
        /// </summary>
        public static string System_Message_ConfirmSubmit {
            get {
                return ResourceManager.GetString("System_Message_ConfirmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认更新? 的本地化字符串。
        /// </summary>
        public static string System_Message_ConfirmUpdate {
            get {
                return ResourceManager.GetString("System_Message_ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据删除失败! 的本地化字符串。
        /// </summary>
        public static string System_Message_DeleteFail {
            get {
                return ResourceManager.GetString("System_Message_DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据删除成功! 的本地化字符串。
        /// </summary>
        public static string System_Message_DeleteSuccess {
            get {
                return ResourceManager.GetString("System_Message_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据导出成功! 的本地化字符串。
        /// </summary>
        public static string System_Message_ExportSuccess {
            get {
                return ResourceManager.GetString("System_Message_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据导入成功! 的本地化字符串。
        /// </summary>
        public static string System_Message_InportSuccess {
            get {
                return ResourceManager.GetString("System_Message_InportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核退回! 的本地化字符串。
        /// </summary>
        public static string System_Message_Reject {
            get {
                return ResourceManager.GetString("System_Message_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据保存成功! 的本地化字符串。
        /// </summary>
        public static string System_Message_SavedSuccess {
            get {
                return ResourceManager.GetString("System_Message_SavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据保存失败! 的本地化字符串。
        /// </summary>
        public static string System_Message_SaveFail {
            get {
                return ResourceManager.GetString("System_Message_SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据更新失败! 的本地化字符串。
        /// </summary>
        public static string System_Message_UpdateFail {
            get {
                return ResourceManager.GetString("System_Message_UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据更新成功! 的本地化字符串。
        /// </summary>
        public static string System_Message_UpdateSuccess {
            get {
                return ResourceManager.GetString("System_Message_UpdateSuccess", resourceCulture);
            }
        }
    }
}
