//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareidea.Web.UI.Control.Workflow.Designer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shareidea.Web.UI.Control.Workflow.Designer.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string ActivityName {
            get {
                return ResourceManager.GetString("ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string ActivityType {
            get {
                return ResourceManager.GetString("ActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AND_BRANCH 的本地化字符串。
        /// </summary>
        public static string ActivityType_AND_BRANCH {
            get {
                return ResourceManager.GetString("ActivityType_AND_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AND_MERGE 的本地化字符串。
        /// </summary>
        public static string ActivityType_AND_MERGE {
            get {
                return ResourceManager.GetString("ActivityType_AND_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AUTOMATION 的本地化字符串。
        /// </summary>
        public static string ActivityType_AUTOMATION {
            get {
                return ResourceManager.GetString("ActivityType_AUTOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COMPLETION 的本地化字符串。
        /// </summary>
        public static string ActivityType_COMPLETION {
            get {
                return ResourceManager.GetString("ActivityType_COMPLETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DUMMY 的本地化字符串。
        /// </summary>
        public static string ActivityType_DUMMY {
            get {
                return ResourceManager.GetString("ActivityType_DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INITIAL 的本地化字符串。
        /// </summary>
        public static string ActivityType_INITIAL {
            get {
                return ResourceManager.GetString("ActivityType_INITIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INTERACTION 的本地化字符串。
        /// </summary>
        public static string ActivityType_INTERACTION {
            get {
                return ResourceManager.GetString("ActivityType_INTERACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OR_BRANCH 的本地化字符串。
        /// </summary>
        public static string ActivityType_OR_BRANCH {
            get {
                return ResourceManager.GetString("ActivityType_OR_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OR_MERGE 的本地化字符串。
        /// </summary>
        public static string ActivityType_OR_MERGE {
            get {
                return ResourceManager.GetString("ActivityType_OR_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SUBPROCESS 的本地化字符串。
        /// </summary>
        public static string ActivityType_SUBPROCESS {
            get {
                return ResourceManager.GetString("ActivityType_SUBPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOTE_MERGE 的本地化字符串。
        /// </summary>
        public static string ActivityType_VOTE_MERGE {
            get {
                return ResourceManager.GetString("ActivityType_VOTE_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Activity 的本地化字符串。
        /// </summary>
        public static string Button_AddActivity {
            get {
                return ResourceManager.GetString("Button_AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Label 的本地化字符串。
        /// </summary>
        public static string Button_AddLabel {
            get {
                return ResourceManager.GetString("Button_AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Rule 的本地化字符串。
        /// </summary>
        public static string Button_AddRule {
            get {
                return ResourceManager.GetString("Button_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancle 的本地化字符串。
        /// </summary>
        public static string Button_Cancle {
            get {
                return ResourceManager.GetString("Button_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Button_ClearContainer {
            get {
                return ResourceManager.GetString("Button_ClearContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatePicture 的本地化字符串。
        /// </summary>
        public static string Button_CreatePicture {
            get {
                return ResourceManager.GetString("Button_CreatePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Button_ExportToXml {
            get {
                return ResourceManager.GetString("Button_ExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Button_ImportFromXml {
            get {
                return ResourceManager.GetString("Button_ImportFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        public static string Button_Previous {
            get {
                return ResourceManager.GetString("Button_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        public static string Button_Zoom {
            get {
                return ResourceManager.GetString("Button_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 will delete Object,continue? 的本地化字符串。
        /// </summary>
        public static string Comfirm_Delete {
            get {
                return ResourceManager.GetString("Comfirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        public static string ContainerHeight {
            get {
                return ResourceManager.GetString("ContainerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string ContainerWidth {
            get {
                return ResourceManager.GetString("ContainerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string LineType {
            get {
                return ResourceManager.GetString("LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlignBottom 的本地化字符串。
        /// </summary>
        public static string Menu_AlignBottom {
            get {
                return ResourceManager.GetString("Menu_AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlignLeft 的本地化字符串。
        /// </summary>
        public static string Menu_AlignLeft {
            get {
                return ResourceManager.GetString("Menu_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlignRight 的本地化字符串。
        /// </summary>
        public static string Menu_AlignRight {
            get {
                return ResourceManager.GetString("Menu_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlignTop 的本地化字符串。
        /// </summary>
        public static string Menu_AlignTop {
            get {
                return ResourceManager.GetString("Menu_AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_CopyActivity {
            get {
                return ResourceManager.GetString("Menu_CopyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_CopyLabel {
            get {
                return ResourceManager.GetString("Menu_CopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_CopyRule {
            get {
                return ResourceManager.GetString("Menu_CopyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_CopySelected {
            get {
                return ResourceManager.GetString("Menu_CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteActivity {
            get {
                return ResourceManager.GetString("Menu_DeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteLabel {
            get {
                return ResourceManager.GetString("Menu_DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteRule {
            get {
                return ResourceManager.GetString("Menu_DeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteSelected {
            get {
                return ResourceManager.GetString("Menu_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string Menu_ModifyActivity {
            get {
                return ResourceManager.GetString("Menu_ModifyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string Menu_ModifyRule {
            get {
                return ResourceManager.GetString("Menu_ModifyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowGridLines 的本地化字符串。
        /// </summary>
        public static string Menu_ShowGridLines {
            get {
                return ResourceManager.GetString("Menu_ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 begin-activitity can not have pre-activity. 的本地化字符串。
        /// </summary>
        public static string Message_BeginActivitiesCanNotHavePreactivity {
            get {
                return ResourceManager.GetString("Message_BeginActivitiesCanNotHavePreactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 begin and end activity  can not be the same. 的本地化字符串。
        /// </summary>
        public static string Message_BeginAndEndActivityCanNotBeTheSame {
            get {
                return ResourceManager.GetString("Message_BeginAndEndActivityCanNotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 branch-activity only have one pre-activity. 的本地化字符串。
        /// </summary>
        public static string Message_BranchActivityOnlyHaveOnePreactivity {
            get {
                return ResourceManager.GetString("Message_BranchActivityOnlyHaveOnePreactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can not have pre-activity. 的本地化字符串。
        /// </summary>
        public static string Message_CanNotHavePreactivity {
            get {
                return ResourceManager.GetString("Message_CanNotHavePreactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 end-activitity can not have follow-up activitiy. 的本地化字符串。
        /// </summary>
        public static string Message_EndActivityCanNotHaveFollowUpActivitiy {
            get {
                return ResourceManager.GetString("Message_EndActivityCanNotHaveFollowUpActivitiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 merge-activitity  only have one follow-up activitiy. 的本地化字符串。
        /// </summary>
        public static string Message_MergeActivityOnlyHaveAFollowUpActivity {
            get {
                return ResourceManager.GetString("Message_MergeActivityOnlyHaveAFollowUpActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please modify workflow  in accordance with tips. 的本地化字符串。
        /// </summary>
        public static string Message_ModifyWorkFlowByTip {
            get {
                return ResourceManager.GetString("Message_ModifyWorkFlowByTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rule must be linked to begin-activitiy. 的本地化字符串。
        /// </summary>
        public static string Message_MustBeLinkToBeginActivity {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToBeginActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rule must be linked to begin-activitiy and end-activity. 的本地化字符串。
        /// </summary>
        public static string Message_MustBeLinkToBeginAndEndActivity {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToBeginAndEndActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rule must be linked to end-activitiy. 的本地化字符串。
        /// </summary>
        public static string Message_MustBeLinkToEndActivity {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToEndActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have at least one end-activity. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveAtLeastOneEndActivity {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOneEndActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have at least one follow-up activity. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveAtLeastOneFollowUpActivity {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOneFollowUpActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have at least one pre-activity. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveAtLeastOnePreactivity {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOnePreactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have only one begin-activity. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveOnlyOneBeginActivity {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOneBeginActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have only one follow-up activity 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveOnlyOneFollowUpActivity {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOneFollowUpActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have only one pre-activity. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveOnlyOnePreactivity {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOnePreactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not have follow-up activity. 的本地化字符串。
        /// </summary>
        public static string Message_NotHaveFollowUpActivity {
            get {
                return ResourceManager.GetString("Message_NotHaveFollowUpActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 require the installation of pre-and follow-up activities. 的本地化字符串。
        /// </summary>
        public static string Message_RequireTheInstallationOfPreAndFollowupActivity {
            get {
                return ResourceManager.GetString("Message_RequireTheInstallationOfPreAndFollowupActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkFlow had saved! 的本地化字符串。
        /// </summary>
        public static string Message_Saved {
            get {
                return ResourceManager.GetString("Message_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The same rule that already exists. 的本地化字符串。
        /// </summary>
        public static string Message_TheSameRuleThatAlreadyExist {
            get {
                return ResourceManager.GetString("Message_TheSameRuleThatAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewActivity 的本地化字符串。
        /// </summary>
        public static string NewActivity {
            get {
                return ResourceManager.GetString("NewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewLabel 的本地化字符串。
        /// </summary>
        public static string NewLable {
            get {
                return ResourceManager.GetString("NewLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewRule 的本地化字符串。
        /// </summary>
        public static string NewRule {
            get {
                return ResourceManager.GetString("NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        public static string RepeatDirection {
            get {
                return ResourceManager.GetString("RepeatDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal 的本地化字符串。
        /// </summary>
        public static string RepeatDirection_Horizontal {
            get {
                return ResourceManager.GetString("RepeatDirection_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical 的本地化字符串。
        /// </summary>
        public static string RepeatDirection_Vertical {
            get {
                return ResourceManager.GetString("RepeatDirection_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditon 的本地化字符串。
        /// </summary>
        public static string RuleCondition {
            get {
                return ResourceManager.GetString("RuleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        public static string RuleLineType_Line {
            get {
                return ResourceManager.GetString("RuleLineType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polyline 的本地化字符串。
        /// </summary>
        public static string RuleLineType_Polyline {
            get {
                return ResourceManager.GetString("RuleLineType_Polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubFlow 的本地化字符串。
        /// </summary>
        public static string SubFlow {
            get {
                return ResourceManager.GetString("SubFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string WorkFlowName {
            get {
                return ResourceManager.GetString("WorkFlowName", resourceCulture);
            }
        }
    }
}
