//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesClient.WorkFlowSoap")]
    public interface WorkFlowSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetWorkFlowList", ReplyAction="*")]
        System.IAsyncResult BeginGetWorkFlowList(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListRequest request, System.AsyncCallback callback, object asyncState);
        
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListResponse EndGetWorkFlowList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetWorkFlowXML", ReplyAction="*")]
        System.IAsyncResult BeginGetWorkFlowXML(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLRequest request, System.AsyncCallback callback, object asyncState);
        
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLResponse EndGetWorkFlowXML(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DeleteWorkFlow", ReplyAction="*")]
        System.IAsyncResult BeginDeleteWorkFlow(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowRequest request, System.AsyncCallback callback, object asyncState);
        
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowResponse EndDeleteWorkFlow(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UpdateWorkFlowXML", ReplyAction="*")]
        System.IAsyncResult BeginUpdateWorkFlowXML(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLRequest request, System.AsyncCallback callback, object asyncState);
        
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLResponse EndUpdateWorkFlowXML(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetPostList", ReplyAction="*")]
        System.IAsyncResult BeginGetPostList(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListRequest request, System.AsyncCallback callback, object asyncState);
        
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListResponse EndGetPostList(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkFlowListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWorkFlowList", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListRequestBody Body;
        
        public GetWorkFlowListRequest() {
        }
        
        public GetWorkFlowListRequest(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWorkFlowListRequestBody {
        
        public GetWorkFlowListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkFlowListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWorkFlowListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListResponseBody Body;
        
        public GetWorkFlowListResponse() {
        }
        
        public GetWorkFlowListResponse(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWorkFlowListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWorkFlowListResult;
        
        public GetWorkFlowListResponseBody() {
        }
        
        public GetWorkFlowListResponseBody(string GetWorkFlowListResult) {
            this.GetWorkFlowListResult = GetWorkFlowListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkFlowXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWorkFlowXML", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLRequestBody Body;
        
        public GetWorkFlowXMLRequest() {
        }
        
        public GetWorkFlowXMLRequest(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWorkFlowXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string workflowID;
        
        public GetWorkFlowXMLRequestBody() {
        }
        
        public GetWorkFlowXMLRequestBody(string workflowID) {
            this.workflowID = workflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkFlowXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWorkFlowXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLResponseBody Body;
        
        public GetWorkFlowXMLResponse() {
        }
        
        public GetWorkFlowXMLResponse(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWorkFlowXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWorkFlowXMLResult;
        
        public GetWorkFlowXMLResponseBody() {
        }
        
        public GetWorkFlowXMLResponseBody(string GetWorkFlowXMLResult) {
            this.GetWorkFlowXMLResult = GetWorkFlowXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWorkFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWorkFlow", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowRequestBody Body;
        
        public DeleteWorkFlowRequest() {
        }
        
        public DeleteWorkFlowRequest(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteWorkFlowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string workflowID;
        
        public DeleteWorkFlowRequestBody() {
        }
        
        public DeleteWorkFlowRequestBody(string workflowID) {
            this.workflowID = workflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWorkFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWorkFlowResponse", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowResponseBody Body;
        
        public DeleteWorkFlowResponse() {
        }
        
        public DeleteWorkFlowResponse(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteWorkFlowResponseBody {
        
        public DeleteWorkFlowResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWorkFlowXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWorkFlowXML", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLRequestBody Body;
        
        public UpdateWorkFlowXMLRequest() {
        }
        
        public UpdateWorkFlowXMLRequest(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWorkFlowXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string workFlowXml;
        
        public UpdateWorkFlowXMLRequestBody() {
        }
        
        public UpdateWorkFlowXMLRequestBody(string workFlowXml) {
            this.workFlowXml = workFlowXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWorkFlowXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWorkFlowXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLResponseBody Body;
        
        public UpdateWorkFlowXMLResponse() {
        }
        
        public UpdateWorkFlowXMLResponse(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateWorkFlowXMLResponseBody {
        
        public UpdateWorkFlowXMLResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostList", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListRequestBody Body;
        
        public GetPostListRequest() {
        }
        
        public GetPostListRequest(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPostListRequestBody {
        
        public GetPostListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListResponseBody Body;
        
        public GetPostListResponse() {
        }
        
        public GetPostListResponse(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPostListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPostListResult;
        
        public GetPostListResponseBody() {
        }
        
        public GetPostListResponseBody(string GetPostListResult) {
            this.GetPostListResult = GetPostListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorkFlowSoapChannel : Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkFlowListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkFlowListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkFlowXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkFlowXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPostListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPostListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkFlowSoapClient : System.ServiceModel.ClientBase<Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap>, Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap {
        
        private BeginOperationDelegate onBeginGetWorkFlowListDelegate;
        
        private EndOperationDelegate onEndGetWorkFlowListDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkFlowListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWorkFlowXMLDelegate;
        
        private EndOperationDelegate onEndGetWorkFlowXMLDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkFlowXMLCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteWorkFlowDelegate;
        
        private EndOperationDelegate onEndDeleteWorkFlowDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteWorkFlowCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateWorkFlowXMLDelegate;
        
        private EndOperationDelegate onEndUpdateWorkFlowXMLDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateWorkFlowXMLCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPostListDelegate;
        
        private EndOperationDelegate onEndGetPostListDelegate;
        
        private System.Threading.SendOrPostCallback onGetPostListCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WorkFlowSoapClient() {
        }
        
        public WorkFlowSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkFlowSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<GetWorkFlowListCompletedEventArgs> GetWorkFlowListCompleted;
        
        public event System.EventHandler<GetWorkFlowXMLCompletedEventArgs> GetWorkFlowXMLCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteWorkFlowCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateWorkFlowXMLCompleted;
        
        public event System.EventHandler<GetPostListCompletedEventArgs> GetPostListCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.BeginGetWorkFlowList(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkFlowList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetWorkFlowList(System.AsyncCallback callback, object asyncState) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListRequest inValue = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListRequest();
            inValue.Body = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListRequestBody();
            return ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).BeginGetWorkFlowList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListResponse Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.EndGetWorkFlowList(System.IAsyncResult result) {
            return base.Channel.EndGetWorkFlowList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetWorkFlowList(System.IAsyncResult result) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListResponse retVal = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).EndGetWorkFlowList(result);
            return retVal.Body.GetWorkFlowListResult;
        }
        
        private System.IAsyncResult OnBeginGetWorkFlowList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetWorkFlowList(callback, asyncState);
        }
        
        private object[] OnEndGetWorkFlowList(System.IAsyncResult result) {
            string retVal = this.EndGetWorkFlowList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkFlowListCompleted(object state) {
            if ((this.GetWorkFlowListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkFlowListCompleted(this, new GetWorkFlowListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkFlowListAsync() {
            this.GetWorkFlowListAsync(null);
        }
        
        public void GetWorkFlowListAsync(object userState) {
            if ((this.onBeginGetWorkFlowListDelegate == null)) {
                this.onBeginGetWorkFlowListDelegate = new BeginOperationDelegate(this.OnBeginGetWorkFlowList);
            }
            if ((this.onEndGetWorkFlowListDelegate == null)) {
                this.onEndGetWorkFlowListDelegate = new EndOperationDelegate(this.OnEndGetWorkFlowList);
            }
            if ((this.onGetWorkFlowListCompletedDelegate == null)) {
                this.onGetWorkFlowListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkFlowListCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkFlowListDelegate, null, this.onEndGetWorkFlowListDelegate, this.onGetWorkFlowListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.BeginGetWorkFlowXML(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkFlowXML(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetWorkFlowXML(string workflowID, System.AsyncCallback callback, object asyncState) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLRequest inValue = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLRequest();
            inValue.Body = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLRequestBody();
            inValue.Body.workflowID = workflowID;
            return ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).BeginGetWorkFlowXML(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLResponse Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.EndGetWorkFlowXML(System.IAsyncResult result) {
            return base.Channel.EndGetWorkFlowXML(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetWorkFlowXML(System.IAsyncResult result) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLResponse retVal = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).EndGetWorkFlowXML(result);
            return retVal.Body.GetWorkFlowXMLResult;
        }
        
        private System.IAsyncResult OnBeginGetWorkFlowXML(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string workflowID = ((string)(inValues[0]));
            return this.BeginGetWorkFlowXML(workflowID, callback, asyncState);
        }
        
        private object[] OnEndGetWorkFlowXML(System.IAsyncResult result) {
            string retVal = this.EndGetWorkFlowXML(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkFlowXMLCompleted(object state) {
            if ((this.GetWorkFlowXMLCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkFlowXMLCompleted(this, new GetWorkFlowXMLCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkFlowXMLAsync(string workflowID) {
            this.GetWorkFlowXMLAsync(workflowID, null);
        }
        
        public void GetWorkFlowXMLAsync(string workflowID, object userState) {
            if ((this.onBeginGetWorkFlowXMLDelegate == null)) {
                this.onBeginGetWorkFlowXMLDelegate = new BeginOperationDelegate(this.OnBeginGetWorkFlowXML);
            }
            if ((this.onEndGetWorkFlowXMLDelegate == null)) {
                this.onEndGetWorkFlowXMLDelegate = new EndOperationDelegate(this.OnEndGetWorkFlowXML);
            }
            if ((this.onGetWorkFlowXMLCompletedDelegate == null)) {
                this.onGetWorkFlowXMLCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkFlowXMLCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkFlowXMLDelegate, new object[] {
                        workflowID}, this.onEndGetWorkFlowXMLDelegate, this.onGetWorkFlowXMLCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.BeginDeleteWorkFlow(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteWorkFlow(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDeleteWorkFlow(string workflowID, System.AsyncCallback callback, object asyncState) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowRequest inValue = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowRequest();
            inValue.Body = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowRequestBody();
            inValue.Body.workflowID = workflowID;
            return ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).BeginDeleteWorkFlow(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowResponse Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.EndDeleteWorkFlow(System.IAsyncResult result) {
            return base.Channel.EndDeleteWorkFlow(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndDeleteWorkFlow(System.IAsyncResult result) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowResponse retVal = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).EndDeleteWorkFlow(result);
        }
        
        private System.IAsyncResult OnBeginDeleteWorkFlow(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string workflowID = ((string)(inValues[0]));
            return this.BeginDeleteWorkFlow(workflowID, callback, asyncState);
        }
        
        private object[] OnEndDeleteWorkFlow(System.IAsyncResult result) {
            this.EndDeleteWorkFlow(result);
            return null;
        }
        
        private void OnDeleteWorkFlowCompleted(object state) {
            if ((this.DeleteWorkFlowCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteWorkFlowCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteWorkFlowAsync(string workflowID) {
            this.DeleteWorkFlowAsync(workflowID, null);
        }
        
        public void DeleteWorkFlowAsync(string workflowID, object userState) {
            if ((this.onBeginDeleteWorkFlowDelegate == null)) {
                this.onBeginDeleteWorkFlowDelegate = new BeginOperationDelegate(this.OnBeginDeleteWorkFlow);
            }
            if ((this.onEndDeleteWorkFlowDelegate == null)) {
                this.onEndDeleteWorkFlowDelegate = new EndOperationDelegate(this.OnEndDeleteWorkFlow);
            }
            if ((this.onDeleteWorkFlowCompletedDelegate == null)) {
                this.onDeleteWorkFlowCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteWorkFlowCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteWorkFlowDelegate, new object[] {
                        workflowID}, this.onEndDeleteWorkFlowDelegate, this.onDeleteWorkFlowCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.BeginUpdateWorkFlowXML(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateWorkFlowXML(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUpdateWorkFlowXML(string workFlowXml, System.AsyncCallback callback, object asyncState) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLRequest inValue = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLRequest();
            inValue.Body = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLRequestBody();
            inValue.Body.workFlowXml = workFlowXml;
            return ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).BeginUpdateWorkFlowXML(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLResponse Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.EndUpdateWorkFlowXML(System.IAsyncResult result) {
            return base.Channel.EndUpdateWorkFlowXML(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndUpdateWorkFlowXML(System.IAsyncResult result) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLResponse retVal = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).EndUpdateWorkFlowXML(result);
        }
        
        private System.IAsyncResult OnBeginUpdateWorkFlowXML(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string workFlowXml = ((string)(inValues[0]));
            return this.BeginUpdateWorkFlowXML(workFlowXml, callback, asyncState);
        }
        
        private object[] OnEndUpdateWorkFlowXML(System.IAsyncResult result) {
            this.EndUpdateWorkFlowXML(result);
            return null;
        }
        
        private void OnUpdateWorkFlowXMLCompleted(object state) {
            if ((this.UpdateWorkFlowXMLCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateWorkFlowXMLCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateWorkFlowXMLAsync(string workFlowXml) {
            this.UpdateWorkFlowXMLAsync(workFlowXml, null);
        }
        
        public void UpdateWorkFlowXMLAsync(string workFlowXml, object userState) {
            if ((this.onBeginUpdateWorkFlowXMLDelegate == null)) {
                this.onBeginUpdateWorkFlowXMLDelegate = new BeginOperationDelegate(this.OnBeginUpdateWorkFlowXML);
            }
            if ((this.onEndUpdateWorkFlowXMLDelegate == null)) {
                this.onEndUpdateWorkFlowXMLDelegate = new EndOperationDelegate(this.OnEndUpdateWorkFlowXML);
            }
            if ((this.onUpdateWorkFlowXMLCompletedDelegate == null)) {
                this.onUpdateWorkFlowXMLCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateWorkFlowXMLCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateWorkFlowXMLDelegate, new object[] {
                        workFlowXml}, this.onEndUpdateWorkFlowXMLDelegate, this.onUpdateWorkFlowXMLCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.BeginGetPostList(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPostList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetPostList(System.AsyncCallback callback, object asyncState) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListRequest inValue = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListRequest();
            inValue.Body = new Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListRequestBody();
            return ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).BeginGetPostList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListResponse Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap.EndGetPostList(System.IAsyncResult result) {
            return base.Channel.EndGetPostList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetPostList(System.IAsyncResult result) {
            Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListResponse retVal = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap)(this)).EndGetPostList(result);
            return retVal.Body.GetPostListResult;
        }
        
        private System.IAsyncResult OnBeginGetPostList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetPostList(callback, asyncState);
        }
        
        private object[] OnEndGetPostList(System.IAsyncResult result) {
            string retVal = this.EndGetPostList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPostListCompleted(object state) {
            if ((this.GetPostListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPostListCompleted(this, new GetPostListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPostListAsync() {
            this.GetPostListAsync(null);
        }
        
        public void GetPostListAsync(object userState) {
            if ((this.onBeginGetPostListDelegate == null)) {
                this.onBeginGetPostListDelegate = new BeginOperationDelegate(this.OnBeginGetPostList);
            }
            if ((this.onEndGetPostListDelegate == null)) {
                this.onEndGetPostListDelegate = new EndOperationDelegate(this.OnEndGetPostList);
            }
            if ((this.onGetPostListCompletedDelegate == null)) {
                this.onGetPostListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPostListCompleted);
            }
            base.InvokeAsync(this.onBeginGetPostListDelegate, null, this.onEndGetPostListDelegate, this.onGetPostListCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap CreateChannel() {
            return new WorkFlowSoapClientChannel(this);
        }
        
        private class WorkFlowSoapClientChannel : ChannelBase<Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap>, Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap {
            
            public WorkFlowSoapClientChannel(System.ServiceModel.ClientBase<Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.WorkFlowSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetWorkFlowList(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetWorkFlowList", _args, callback, asyncState);
                return _result;
            }
            
            public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListResponse EndGetWorkFlowList(System.IAsyncResult result) {
                object[] _args = new object[0];
                Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListResponse _result = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowListResponse)(base.EndInvoke("GetWorkFlowList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWorkFlowXML(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetWorkFlowXML", _args, callback, asyncState);
                return _result;
            }
            
            public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLResponse EndGetWorkFlowXML(System.IAsyncResult result) {
                object[] _args = new object[0];
                Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLResponse _result = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetWorkFlowXMLResponse)(base.EndInvoke("GetWorkFlowXML", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteWorkFlow(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("DeleteWorkFlow", _args, callback, asyncState);
                return _result;
            }
            
            public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowResponse EndDeleteWorkFlow(System.IAsyncResult result) {
                object[] _args = new object[0];
                Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowResponse _result = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.DeleteWorkFlowResponse)(base.EndInvoke("DeleteWorkFlow", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateWorkFlowXML(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UpdateWorkFlowXML", _args, callback, asyncState);
                return _result;
            }
            
            public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLResponse EndUpdateWorkFlowXML(System.IAsyncResult result) {
                object[] _args = new object[0];
                Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLResponse _result = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.UpdateWorkFlowXMLResponse)(base.EndInvoke("UpdateWorkFlowXML", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPostList(Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetPostList", _args, callback, asyncState);
                return _result;
            }
            
            public Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListResponse EndGetPostList(System.IAsyncResult result) {
                object[] _args = new object[0];
                Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListResponse _result = ((Shareidea.Web.UI.Control.Workflow.Designer.ServicesClient.GetPostListResponse)(base.EndInvoke("GetPostList", _args, result)));
                return _result;
            }
        }
    }
}
